version: '3.8'

services:
  voorjane_server:
    build: ./
    networks:
      - default
  
  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - "./server/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - default

networks:
  default:
